### ISSUE TITLE
Sylius was not able to figure out the current cart

### ISSUE THREAD

**Issue by Prometee** [Sylius/ShopApiPlugin#436]
When using the latest version of this plugin the normal (html) shop is broken because of the override of :
https://github.com/Sylius/ShopApiPlugin/blob/6e25aa869dd58d624c1f9bbf746704909c1986a2/src/Resources/config/services.xml#L73-L76

@diimpp notice it also : 
https://github.com/Sylius/Sylius/issues/10192#issuecomment-474049445

So we have to get ride of it doing this :
```yaml
# config/services.yaml

    # Fix for error from shop-api-plugin
    sylius.context.cart.new:
        class: Sylius\Component\Order\Context\CartContext
        arguments:
            - '@sylius.factory.order'
        tags:
            - { name: 'sylius.context.cart', priority: -999 }
```

Why this is required if we are already deleting every not used carts from the database using in a `crontab` ?
```
bin/console sylius:remove-expired-carts
```
https://docs.sylius.com/en/1.4/cookbook/deployment/cron-jobs.html
