### ISSUE TITLE
Add api for users check

### ISSUE THREAD

**Issue by alexander-schranz** [Sylius/ShopApiPlugin#539]
Currently the complete action errors when try to complete with an exist email address to avoid this an additional api should be added to check if a user with that email address exist in the checkout.

The Shop Bundle is doing this over `sylius_shop_ajax_user_check_action` route which controller could be used for it like for the passwords where it also points to shop controllers.

```
sylius_shop_api_check_user:
    path: /shop-api/users/check
    methods: GET
    defaults:
        _controller: sylius.controller.shop_user:showAction
```
