### ISSUE TITLE
Cropped Cached Images Under ShopApi Folder

### ISSUE THREAD

**Issue by wyamout** [Sylius/ShopApiPlugin#693]
My cached images are created under sylius_shop_api in media/cache/ folder.

All images are being cropped for some reason. Anywhere I can control this?

**Comment by mamazu** [comment]
The image generation is configured with the LIIP Image bundle. Maybe you can debug it's configuration to see if the shopapi filter is configured incorrectly.

**Comment by wyamout** [comment]
Yep that was true .Added the below now all good. Thank you

```
filter_sets:
        sylius_shop_api:
            filters:
                downscale:
                    max: [1980, 1280]
```
