### ISSUE TITLE
Getting "Format 'html' not supported, handler must be implemented" on GET requests

### ISSUE THREAD

**Issue by medteck** [Sylius/ShopApiPlugin#721]
When I try to retrieve data with A GET request (ex: `/shop-api/products/by-code/abc`), I'm getting this response from the API :

```
{
    "code": 401,
    "message": "Invalid credentials."
}
```

Here's my configuration in `config/packages/_sylius_shop_api.yaml` : 
```
imports:
    - { resource: "@SyliusShopApiPlugin/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopApiPlugin/Resources/config/app/sylius_mailer.yml" }

# config/packages/fos_rest.yaml

fos_rest:
    view:
        formats:
            json: true
    format_listener:
        rules:
            - { path: '^/shop-api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
            - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }
```

As you can see, the file is as described in the README of the package.

I tried everything I saw on Stackoverflow (related to api_platform) and none of those solutions worked.
